# Configuration for Documentation API
api:
  base_url: "https://text.pollinations.ai/openai/v1/chat/completions"
  token: "16VFCmZKXdSxDlpU"
  retries: 30
  default_model: "gpt-4o"
  default_temperature: 0.7
  max_tokens: 12000

database:
  path: "llm_docs.db"
  cache_size: -20000
  synchronous: "NORMAL"

logging:
  level: "INFO"
  file: "doc_api.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
